# coding: utf-8

NOIR = (0, 0, 0)
GRIS_FONCE = (50, 50, 50)
GRIS_MOYEN = (90, 90, 90)
GRIS_CLAIR = (130, 130, 130)
BLANC = (255, 255, 255)
BLEU = (0, 0, 255)
VERT = (52, 175, 0)
ROUGE = (255, 0, 0)
ORANGE = (255, 127, 0)
JAUNE = (255, 230, 0)

FPS = 100
CAPTION = 'Logimage'

COULEUR_FOND = (200, 200, 200)

LARGEUR = 1360
HAUTEUR = 700

DEFAULT_POLICE = None, 35

DEFAULT_TAILLE_GRILLE = 20, 15
MARGE_GRILLE_BORD_HAUT = 100
MARGE_GRILLE_BORD_BAS = 20
MARGE_GRILLE_BORD_DROITE = 20
MARGE_GRILLE_BORD_GAUCHE = 330
MARGE_BOUTON = 20

COULEUR_TITRE = NOIR
TAILLE_TITRE = 80
CONTOURS_TITRE_SELECTIONNE = GRIS_MOYEN, 4
MARGE_TITRE = 15
DEFAULT_TITRE = 'Logimage'
LONGEUR_TITRE_MAX = 30

COULEUR_QUADRILLAGE = NOIR
COULEUR_CASE_PLEINE = (20, 20, 20)
COULEUR_CASE_VIDE = BLANC
COEF_TAILLE_QUADRILLAGE = 0.06
COEF_TAILLE_QUADRILLAGE_PRINCIPALE_ECART = 0.04
QUADRILLAGE_PRINCIPALE = 5
COEF_TAILLE_POLICE = 1.2
COULEUR_NB = NOIR

CASE_INCONNUE = "?"
COULEUR_CASE_INCONNUE = (180, 0, 0)

BOUTON_SUPPR_LIGNE = 0
BOUTON_SUPPR_COLONNE = 1
BOUTON_SUPPR_GROUPE_LIGNES = 2
BOUTON_SUPPR_GROUPE_COLONNES = 3
BOUTON_AJOUT_LIGNE = 4
BOUTON_AJOUT_COLONNE = 5
BOUTON_AJOUT_GROUPE_LIGNES = 6
BOUTON_AJOUT_GROUPE_COLONNES = 7
BOUTON_CREER_LOGIMAGE = 8

DIC_TEXTES_BOUTONS = {
    BOUTON_SUPPR_LIGNE: 'Supprimer 1 ligne',
    BOUTON_SUPPR_COLONNE: 'Supprimer 1 colonne',
    BOUTON_SUPPR_GROUPE_LIGNES: f'Supprimer {QUADRILLAGE_PRINCIPALE} lignes',
    BOUTON_SUPPR_GROUPE_COLONNES: f'Supprimer {QUADRILLAGE_PRINCIPALE} colonnes',
    BOUTON_AJOUT_LIGNE: 'Ajouter 1 ligne',
    BOUTON_AJOUT_COLONNE: 'Ajouter 1 colonne',
    BOUTON_AJOUT_GROUPE_LIGNES: f'Ajouter {QUADRILLAGE_PRINCIPALE} lignes',
    BOUTON_AJOUT_GROUPE_COLONNES: f'Ajouter {QUADRILLAGE_PRINCIPALE} colonnes',
    BOUTON_CREER_LOGIMAGE: 'Créer le logimage'
}

STYLE_BOUTON_VERT = ((0, 40, 3), (90, 135, 95), 3, (0, 40, 3))
STYLE_BOUTON_ROUGE = ((96, 0, 0), (181, 99, 99), 3, (96, 0, 0))

DIC_STYLES_BOUTONS = {
    BOUTON_SUPPR_LIGNE: STYLE_BOUTON_ROUGE,
    BOUTON_SUPPR_COLONNE: STYLE_BOUTON_ROUGE,
    BOUTON_SUPPR_GROUPE_LIGNES: STYLE_BOUTON_ROUGE,
    BOUTON_SUPPR_GROUPE_COLONNES: STYLE_BOUTON_ROUGE,
    BOUTON_AJOUT_LIGNE: STYLE_BOUTON_VERT,
    BOUTON_AJOUT_COLONNE: STYLE_BOUTON_VERT,
    BOUTON_AJOUT_GROUPE_LIGNES: STYLE_BOUTON_VERT,
    BOUTON_AJOUT_GROUPE_COLONNES: STYLE_BOUTON_VERT,
    BOUTON_CREER_LOGIMAGE: (NOIR, (70, 70, 70), 5, NOIR)
}
LISTE_ORDRE_BOUTONS = [BOUTON_AJOUT_LIGNE,
                       BOUTON_AJOUT_COLONNE,
                       BOUTON_AJOUT_GROUPE_LIGNES,
                       BOUTON_AJOUT_GROUPE_COLONNES,
                       BOUTON_SUPPR_LIGNE,
                       BOUTON_SUPPR_COLONNE,
                       BOUTON_SUPPR_GROUPE_LIGNES,
                       BOUTON_SUPPR_GROUPE_COLONNES,
                       BOUTON_CREER_LOGIMAGE]

COULEUR_SUPPRESSION = ROUGE, 130
COULEUR_AJOUT = VERT, 150
COEF_TAILLE_AJOUT = 0.4

COTE_CASE_LOGIMAGE = 50
HAUTEUR_BANDEAU_TITRE_LOGIMAGE = 200
TAILLE_TEXTE_TITRE_LOGIMAGE = 180

TEXTE_NB_ETAPES = lambda nb_etapes_logimage: f"IMPOSSIBLE  (Nombre d'étapes : {nb_etapes_logimage[1]}) " \
    if nb_etapes_logimage[0] is None \
    else f"Nombre d'étapes : {nb_etapes_logimage[1]}  (sur {nb_etapes_logimage[0]} cases) "
